services:
    # parser
    feed.parser.chain:
        class: Api43\FeedBundle\Parser\ParserChain

    feed.parser.external:
        class: Api43\FeedBundle\Parser\External
        arguments:
            - "@guzzle.client"
            - 'https://mercury.postlight.com/parser'
            - "%mercury_key%"
        tags:
            -  { name: feed.parser, alias: external }

    feed.parser.internal:
        class: Api43\FeedBundle\Parser\Internal
        arguments:
            - "@graby"
        tags:
            -  { name: feed.parser, alias: internal }
