services:
    # https://coderwall.com/p/4gamjq
    feed.converter.doctrine.mongodb:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments:
            - "@doctrine_mongodb"
        tags:
            - { name: request.param_converter }

    # external service
    imgur.client:
        class: Imgur\Client
        calls:
            - [ setOption, [ 'client_id', %imgur.client_id% ] ]
            - [ setOption, [ 'client_secret', %imgur.client_secret% ] ]

    guzzle.client:
        class: GuzzleHttp\Client
        arguments:
            - %guzzle.options%

    graby:
        class: Graby\Graby
        arguments:
            -
                error_message: false
                extractor:
                    config_builder:
                        site_config:
                            - %kernel.root_dir%/site_config
        calls:
            - [ setLogger, [ "@logger" ] ]
        tags:
            - { name: monolog.logger, channel: graby }

    twitter.client:
        class: TwitterOAuth\TwitterOAuth
        arguments:
            -
                consumer_key: %twitter.consumer_key%
                consumer_secret: %twitter.consumer_secret%
                oauth_token: %twitter.access_token%
                oauth_token_secret: %twitter.access_token_secret%
                output_format: 'array'

    content_import:
        class: Api43\FeedBundle\Content\Import
        arguments:
            - "@simple_pie_proxy"
            - "@content_extractor"
            - "@event_dispatcher"
            - "@doctrine.odm.mongodb.document_manager"
            - "@monolog.logger.import"

    # custom formatter for import commande (below)
    monolog.import.formatter:
        class: Symfony\Bridge\Monolog\Formatter\ConsoleFormatter
        arguments:
            - "[%%datetime%%] %%start_tag%%%%message%%%%end_tag%% %%context%% %%extra%%\n"

    content_extractor:
        class: Api43\FeedBundle\Content\Extractor
        arguments:
            extractor: "@feed.extractor.chain"
            improver: "@feed.improver.chain"
            parser: "@feed.parser.chain"

    simple_pie_proxy:
        class: Api43\FeedBundle\Xml\SimplePieProxy
        arguments:
            cache: "%kernel.root_dir%/cache/simplepie/"
            item_limit: 20
            enable_cache: false

    xml_render:
        class: Api43\FeedBundle\Xml\Render
        arguments:
            generator: %domain%
            doctrine: "@doctrine.odm.mongodb.document_manager"
            router: "@router"

    feeditem.ping_hub:
        class: Api43\FeedBundle\EventListener\FeedItemSubscriber
        arguments:
            hub: "http://pubsubhubbub.appspot.com"
            router: "@router"
            client: "@guzzle.client"
        tags:
            - { name: kernel.event_listener, event: api43_feed.after_item_cached, method: pingHub }

    # validator
    validator.rss.valid_rss:
        class: Api43\FeedBundle\Validator\Constraints\ConstraintRssValidator
        arguments:
            - "@guzzle.client"
        tags:
            - { name: validator.constraint_validator, alias: valid_rss }

    # feed extractor
    feed.extractor.chain:
        class: Api43\FeedBundle\Extractor\ExtractorChain

    feed.extractor.imgur:
        class: Api43\FeedBundle\Extractor\Imgur
        arguments:
            - "@imgur.client"
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: imgur }

    feed.extractor.twitter:
        class: Api43\FeedBundle\Extractor\Twitter
        arguments:
            - "@twitter.client"
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: twitter }

    feed.extractor.tumblr:
        class: Api43\FeedBundle\Extractor\Tumblr
        arguments:
            - %tumblr.api_key%
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: tumblr }

    feed.extractor.vine:
        class: Api43\FeedBundle\Extractor\Vine
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: vine }

    feed.extractor.instagram:
        class: Api43\FeedBundle\Extractor\Instagram
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: instagram }

    feed.extractor.vidme:
        class: Api43\FeedBundle\Extractor\Vidme
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: vidme }

    feed.extractor.gfycat:
        class: Api43\FeedBundle\Extractor\Gfycat
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: gfycat }

    feed.extractor.flickr:
        class: Api43\FeedBundle\Extractor\Flickr
        arguments:
            - %flickr.api_key%
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: flickr }

    feed.extractor.github:
        class: Api43\FeedBundle\Extractor\Github
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: github }

    feed.extractor.deviantart:
        class: Api43\FeedBundle\Extractor\Deviantart
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: deviantart }

    feed.extractor.camplus:
        class: Api43\FeedBundle\Extractor\Camplus
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: camplus }

    feed.extractor.soundcloud:
        class: Api43\FeedBundle\Extractor\Soundcloud
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: soundcloud }

    feed.extractor.vimeo:
        class: Api43\FeedBundle\Extractor\Vimeo
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: vimeo }

    feed.extractor.youtube:
        class: Api43\FeedBundle\Extractor\Youtube
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: youtube }

    feed.extractor.dailymotion:
        class: Api43\FeedBundle\Extractor\Dailymotion
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: dailymotion }

    feed.extractor.spotify:
        class: Api43\FeedBundle\Extractor\Spotify
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: spotify }

    feed.extractor.hackernews:
        class: Api43\FeedBundle\Extractor\HackerNews
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: hackernews }

    feed.extractor.rue89:
        class: Api43\FeedBundle\Extractor\Rue89
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@guzzle.client" ]]
        tags:
            -  { name: feed.extractor, alias: rue89 }

    # improver
    feed.improver.chain:
        class: Api43\FeedBundle\Improver\ImproverChain

    feed.improver.hackernews:
        class: Api43\FeedBundle\Improver\HackerNews
        arguments:
            - "@guzzle.client"
        tags:
            -  { name: feed.improver, alias: hackernews }

    feed.improver.reddit:
        class: Api43\FeedBundle\Improver\Reddit
        arguments:
            - "@guzzle.client"
        tags:
            -  { name: feed.improver, alias: reddit }

    # this one should be the last one (because this is the default one :)
    feed.improver.default_improver:
        class: Api43\FeedBundle\Improver\DefaultImprover
        arguments:
            - "@guzzle.client"
        tags:
            -  { name: feed.improver, alias: default_improver }

    # parser
    feed.parser.chain:
        class: Api43\FeedBundle\Parser\ParserChain

    feed.parser.external:
        class: Api43\FeedBundle\Parser\External
        arguments:
            - "@guzzle.client"
            - 'https://readability.com/api/content/v1/parser'
            - %readability_token%
        tags:
            -  { name: feed.parser, alias: external }

    feed.parser.internal:
        class: Api43\FeedBundle\Parser\Internal
        arguments:
            - "@graby"
        tags:
            -  { name: feed.parser, alias: internal }
