services:
    # https://coderwall.com/p/4gamjq
    feed.converter.doctrine.mongodb:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments: [@doctrine_mongodb]
        tags:
            - { name: request.param_converter }

    # external service
    imgur.client:
        class: Imgur\Client
        calls:
            - [ setOption, [ 'client_id', %imgur.client_id% ] ]
            - [ setOption, [ 'client_secret', %imgur.client_secret% ] ]

    guzzle.client:
        class: Guzzle\Http\Client
        arguments:
            - ''
            - %guzzle.options%

    twitter.client:
        class: TwitterOAuth\TwitterOAuth
        arguments:
            -
                consumer_key: %twitter.consumer_key%
                consumer_secret: %twitter.consumer_secret%
                oauth_token: %twitter.access_token%
                oauth_token_secret: %twitter.access_token_secret%
                output_format: 'array'

    readability_proxy:
        class: Api43\FeedBundle\Readability\Proxy
        arguments:
            extractor: @feed.extractor.chain
            improver: @feed.improver.chain
            parser: @feed.parser.chain

    simple_pie_proxy:
        class: Api43\FeedBundle\Services\SimplePieProxy
        arguments:
            cache: "%kernel.root_dir%/cache/simplepie/"
            item_limit: 20
            enable_cache: false

    rss_render:
        class: Api43\FeedBundle\Services\RssRender
        arguments:
            generator: %domain%
            doctrine: "@doctrine.odm.mongodb.document_manager"
            router: "@router"

    feeditem.ping_hub:
        class: Api43\FeedBundle\EventListener\FeedItemSubscriber
        arguments:
            hub: "http://pubsubhubbub.appspot.com"
            router: "@router"
        tags:
            - { name: kernel.event_listener, event: api43_feed.after_item_cached, method: pingHub }

    # validator
    validator.rss.valid_rss:
        class: Api43\FeedBundle\Validator\Constraints\ConstraintRssValidator
        arguments:
            - @guzzle.client
        tags:
            - { name: validator.constraint_validator, alias: valid_rss }

    # feed extractor
    feed.extractor.chain:
        class: Api43\FeedBundle\Extractor\ExtractorChain

    feed.extractor.imgur:
        class: Api43\FeedBundle\Extractor\Imgur
        arguments:
            - @imgur.client
        tags:
            -  { name: feed.extractor, alias: imgur }

    feed.extractor.twitter:
        class: Api43\FeedBundle\Extractor\Twitter
        arguments:
            - @twitter.client
        tags:
            -  { name: feed.extractor, alias: twitter }

    feed.extractor.tumblr:
        class: Api43\FeedBundle\Extractor\Tumblr
        arguments:
            - @guzzle.client
            - %tumblr.api_key%
        tags:
            -  { name: feed.extractor, alias: tumblr }

    feed.extractor.vine:
        class: Api43\FeedBundle\Extractor\Vine
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.extractor, alias: vine }

    feed.extractor.instagram:
        class: Api43\FeedBundle\Extractor\Instagram
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.extractor, alias: instagram }

    feed.extractor.vidme:
        class: Api43\FeedBundle\Extractor\Vidme
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.extractor, alias: vidme }

    feed.extractor.gfycat:
        class: Api43\FeedBundle\Extractor\Gfycat
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.extractor, alias: gfycat }

    feed.extractor.flickr:
        class: Api43\FeedBundle\Extractor\Flickr
        arguments:
            - @guzzle.client
            - %flickr.api_key%
        tags:
            -  { name: feed.extractor, alias: flickr }

    feed.extractor.github:
        class: Api43\FeedBundle\Extractor\Github
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.extractor, alias: github }

    feed.extractor.deviantart:
        class: Api43\FeedBundle\Extractor\Deviantart
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.extractor, alias: deviantart }

    feed.extractor.camplus:
        class: Api43\FeedBundle\Extractor\Camplus
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.extractor, alias: camplus }

    feed.extractor.soundcloud:
        class: Api43\FeedBundle\Extractor\Soundcloud
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.extractor, alias: soundcloud }

    feed.extractor.vimeo:
        class: Api43\FeedBundle\Extractor\Vimeo
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.extractor, alias: vimeo }

    feed.extractor.youtube:
        class: Api43\FeedBundle\Extractor\Youtube
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.extractor, alias: youtube }

    # improver
    feed.improver.chain:
        class: Api43\FeedBundle\Improver\ImproverChain

    feed.improver.hackernews:
        class: Api43\FeedBundle\Improver\HackerNews
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.improver, alias: hackernews }

    feed.improver.reddit:
        class: Api43\FeedBundle\Improver\Reddit
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.improver, alias: reddit }

    # this one should be the last one (because this is the default one :)
    feed.improver.nothing:
        class: Api43\FeedBundle\Improver\Nothing
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.improver, alias: nothing }

    # parser
    feed.parser.chain:
        class: Api43\FeedBundle\Parser\ParserChain

    feed.parser.external:
        class: Api43\FeedBundle\Parser\External
        arguments:
            - @guzzle.client
            - 'https://readability.com/api/content/v1/parser'
            - %readability_token%
        tags:
            -  { name: feed.parser, alias: external }

    feed.parser.internal:
        class: Api43\FeedBundle\Parser\Internal
        arguments:
            - @guzzle.client
            - %parser.regexps%
        tags:
            -  { name: feed.parser, alias: internal }
