language: php

services:
  - mongodb

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

sudo: false

before_script:
  - composer self-update
  # this trick simulate a "no interaction"
  - printf "\n" | pecl install -f channel://pecl.php.net/apcu-4.0.7 # still no stable version ...
  - printf "\n" | pecl install -f mongo

script:
  - ant prepare
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
