language: php

services:
  - mongodb

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # this trick simulate a "no interaction"
  - printf "\n" | pecl install -f channel://pecl.php.net/apcu-4.0.7 # still no stable version ...
  - printf "\n" | pecl install -f mongo

script:
  - ant prepare
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
