language: php

services:
    - mongodb

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

# run build against nightly but allow them to fail
matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
        - php: hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - composer self-update

before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "7.0" ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then PHPUNIT_FLAGS="--coverage-clover=coverage.clover"; fi;

script:
    - ant prepare
    - phpunit $PHPUNIT_FLAGS

after_script:
    - |
        if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        fi
