imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    assets:
        version: v20151203
        version_format: '%%s?version=%%s'
        base_path: ~
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        name: f43me
        save_path: %kernel.root_dir%/sessions
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        ga_tracking: %google_analytics_code%

doctrine_mongodb:
    connections:
        default:
            server: %database_server%
            options: {}
    default_database: %database_name%
    document_managers:
        default:
            auto_mapping: true
            metadata_cache_driver:
                type: array

stof_doctrine_extensions:
    default_locale: en_US

    mongodb:
        default:
            timestampable: true
            sluggable: true
