parameters:
    # database_driver:   pdo_mysql
    # database_host:     127.0.0.1
    # database_port:     ~
    # database_name:     f43
    # database_user:     root
    # database_password: root

    database_server:   mongodb://localhost:27017
    database_name:     f43me

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
