# auth
login:
    pattern:  /login
    defaults: { _controller: j0k3rFeedBundle:Security:login }

login_check:
    pattern:  /login_check

logout:
    path:     /logout

# feed
feed_dashboard:
    pattern:  /dashboard
    defaults: { _controller: j0k3rFeedBundle:Feed:dashboard }

feed_publicview:
    pattern:  /
    defaults: { _controller: j0k3rFeedBundle:Feed:public }

feed_homepage:
    pattern:  /feeds
    defaults: { _controller: j0k3rFeedBundle:Feed:index }

feed_new:
    pattern:  /feed/new
    defaults: { _controller: j0k3rFeedBundle:Feed:new }

feed_create:
    pattern:  /feed/create
    defaults: { _controller: j0k3rFeedBundle:Feed:create }
    methods:  [POST]

feed_edit:
    pattern:  /feed/{slug}/edit
    defaults: { _controller: j0k3rFeedBundle:Feed:edit }

feed_update:
    pattern:  /feed/{slug}/update
    defaults: { _controller: j0k3rFeedBundle:Feed:update }
    methods:  [POST]

feed_delete:
    pattern:  /feed/{slug}/delete
    defaults: { _controller: j0k3rFeedBundle:Feed:delete }
    methods:  [POST]

# feed item
feeditem_homepage:
    pattern:  /feed/{slug}/items
    defaults: { _controller: j0k3rFeedBundle:FeedItem:index }

feeditem_test:
    pattern:  /feed/{slug}/testItem
    defaults: { _controller: j0k3rFeedBundle:FeedItem:testItem }

feeditem_preview:
    pattern:  /item/{id}/preview
    defaults: { _controller: j0k3rFeedBundle:FeedItem:preview }

feeditem_delete_all:
    pattern:  /feed/{slug}/items/deleteAll
    defaults: { _controller: j0k3rFeedBundle:FeedItem:deleteAll }

# feed log
feedlog_homepage:
    pattern:  /logs
    defaults: { _controller: j0k3rFeedBundle:FeedLog:index }

feedlog_feed:
    pattern:  /feed/{slug}/logs
    defaults: { _controller: j0k3rFeedBundle:FeedLog:feed }

feedlog_delete_all:
    pattern:  /feed/{slug}/logs/deleteAll
    defaults: { _controller: j0k3rFeedBundle:FeedLog:deleteAll }

# api
feedapi_feed:
    path:     /{slug}
    host:     api.{domain}
    defaults: { _controller: j0k3rFeedBundle:FeedApi:index, domain: %domain% }
    requirements:
        domain: %domain%
