parameters:
#    j0k3r_feed.example.class: j0k3r\FeedBundle\Example

services:
    readability_proxy:
        class: j0k3r\FeedBundle\Services\ReadabilityProxy
        arguments:
            token: %readability_token%
            debug: false #%kernel.debug%
            converconvertLinksToFootnotestLink: false
            regex:
                unlikelyCandidates: '/combx|comment|community|disqus|extra|foot|header|menu|remark|rss|shoutbox|sidebar|sponsor|ad-break|agegate|pagination|pager|popup|sharedaddy|addthis|response|slate_associated_bn|reseaux/i'
                okMaybeItsACandidate: '/and|article|body|column|main|shadow/i'
                positive: '/article|body|content|entry|hentry|main|page|attachment|pagination|post|text|blog|story/i'
                negative: '/combx|comment|com-|contact|foot|footer|_nav|footnote|masthead|media|meta|outbrain|promo|related|scroll|shoutbox|sidebar|sponsor|shopping|tags|tool|widget|sharedaddy|addthis/i'
                divToPElements: '/<(a|blockquote|dl|div|img|ol|p|pre|table|ul)/i'
                replaceBrs: '/(<br[^>]*>[ \n\r\t]*){2,}/i'
                replaceFonts: '/<(\/?)font[^>]*>/i'
                normalize: '/\s{2,}/'
                killBreaks: '/(<br\s*\/?>(\s|&nbsp;?)*){1,}/'
                video: '!//(player\.|www\.)?(youtube|vimeo|viddler)\.com!i'
                skipFootnoteLink: '/^\s*(\[?[a-z0-9]{1,2}\]?|^|edit|citation needed)\s*$/i'

    simple_pie_proxy:
        class: j0k3r\FeedBundle\Services\SimplePieProxy
        arguments:
            cache: "%kernel.root_dir%/cache/simplepie/"
            item_limit: 20
            enable_cache: false
