services:
    # external service
    imgur.client:
        class: Imgur\Client
        calls:
            - [ setOption, [ 'client_id', %imgur.client_id% ] ]
            - [ setOption, [ 'client_secret', %imgur.client_secret% ] ]

    guzzle.client:
        class: Guzzle\Http\Client

    readability_proxy:
        class: j0k3r\FeedBundle\Readability\Proxy
        arguments:
            extractor: @feed.extractor.chain
            improver: @feed.improver.chain
            parser: @feed.parser.chain

    simple_pie_proxy:
        class: j0k3r\FeedBundle\Services\SimplePieProxy
        arguments:
            cache: "%kernel.root_dir%/cache/simplepie/"
            item_limit: 20
            enable_cache: false

    rss_render:
        class: j0k3r\FeedBundle\Services\RssRender
        arguments:
            generator: %domain%
            doctrine: "@doctrine.odm.mongodb.document_manager"
            router: "@router"

    feeditem.ping_hub:
        class: j0k3r\FeedBundle\EventListener\FeedItemSubscriber
        arguments:
            hub: "http://pubsubhubbub.appspot.com"
        tags:
            - { name: kernel.event_listener, event: j0k3r_feed.after_item_cached, method: pingHub }

    # validator
    validator.rss.valid_rss:
        class: j0k3r\FeedBundle\Validator\Constraints\ConstraintRssValidator
        arguments:
            - @guzzle.client
        tags:
            - { name: validator.constraint_validator, alias: valid_rss }

    # feed extractor
    feed.extractor.chain:
        class: j0k3r\FeedBundle\Extractor\ExtractorChain

    feed.extractor.imgur:
        class: j0k3r\FeedBundle\Extractor\Imgur
        arguments:
            - @imgur.client
        tags:
            -  { name: feed.extractor, alias: imgur }

    feed.extractor.twitter:
        class: j0k3r\FeedBundle\Extractor\Twitter
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.extractor, alias: twitter }

    feed.extractor.tumblr:
        class: j0k3r\FeedBundle\Extractor\Tumblr
        arguments:
            - @guzzle.client
            - %tumblr.api_key%
        tags:
            -  { name: feed.extractor, alias: tumblr }

    # improver
    feed.improver.chain:
        class: j0k3r\FeedBundle\Improver\ImproverChain

    feed.improver.hackernews:
        class: j0k3r\FeedBundle\Improver\HackerNews
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.improver, alias: hackernews }

    feed.improver.reddit:
        class: j0k3r\FeedBundle\Improver\Reddit
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.improver, alias: reddit }

    # this one should be the last one (because this is the default one :)
    feed.improver.nothing:
        class: j0k3r\FeedBundle\Improver\Nothing
        arguments:
            - @guzzle.client
        tags:
            -  { name: feed.improver, alias: nothing }

    # parser
    feed.parser.chain:
        class: j0k3r\FeedBundle\Parser\ParserChain

    feed.parser.external:
        class: j0k3r\FeedBundle\Parser\External
        arguments:
            - @guzzle.client
            - 'https://readability.com/api/content/v1/parser'
            - %readability_token%
        tags:
            -  { name: feed.parser, alias: external }

    feed.parser.internal:
        class: j0k3r\FeedBundle\Parser\Internal
        arguments:
            - @guzzle.client
            - %parser.regexps%
        tags:
            -  { name: feed.parser, alias: internal }
